dev-erlang/p1_pam: Move to dev-erlang/epam
Upstream has eventually decided on the name and it's "epam" rather than
"p1_pam".

diff --git a/net-im/ejabberd/files/epam-wrapper b/net-im/ejabberd/files/epam-wrapper
--- a/net-im/ejabberd/files/epam-wrapper
+++ b/net-im/ejabberd/files/epam-wrapper
@@ -2,19 +2,19 @@
 
 ERL_LIBS=/usr/lib/erlang/lib
 
-for bin in "$ERL_LIBS"/p1_pam-*/priv/bin/epam; do
+for bin in "$ERL_LIBS"/epam-*/priv/bin/epam; do
 	if [ -x "$bin" ]; then
 		if [ -z "$epam" ]; then
 			epam="$bin"
 		else
-			echo "Multiple p1_pam libraries - don't know what to do" >&2
+			echo "Multiple epam libraries - don't know what to do" >&2
 			exit 1
 		fi
 	fi
 done
 
 if [ -z "$epam" ]; then
-	echo "Couldn't find p1_pam package" >&2
+	echo "Couldn't find epam package" >&2
 	exit 1
 fi
 
