games-action/supermariowar: improvements.
This commit:
* enables png and jpeg USE flags on media-libs/sdl-image
* enables vorbis USE flag on media-libs/sdl-mixer
* modifies dynamically the smw_serverdir variable in swmd init script.

Package-Manager: Portage-2.3.6, Repoman-2.3.1

diff --git a/games-action/supermariowar/files/smwd.initd b/games-action/supermariowar/files/smwd.initd
--- a/games-action/supermariowar/files/smwd.initd
+++ b/games-action/supermariowar/files/smwd.initd
@@ -7,7 +7,7 @@ command_background="true"
 pidfile="/var/run/${RC_SVCNAME}.pid"
 name="Super Mario War server"
 description="The Super Mario War server process is in charge of hosting Super Mario War games"
-smw_server_dir="/usr/share/supermariowar-2.0_beta1/server"
+smw_serverdir="@SMW_SERVERDIR@"
 
 depend() {
     use net
@@ -15,11 +15,11 @@ depend() {
 }
 
 start() {
-    if [[ ! -d "${smw_server_dir}" ]]; then
-        eerror "Cannot cd into ${smw_server_dir}"
+    if [[ ! -d "${smw_serverdir}" ]]; then
+        eerror "Cannot cd into ${smw_serverdir}"
         return 1
     fi
-    cd "${smw_server_dir}" || return 1
+    cd "${smw_serverdir}" || return 1
     ebegin "Starting ${name}"
     start-stop-daemon \
         --start \
