net-misc/dropbox: improvements to init.d script
Signed-off-by: Robert W Dyer <sluidfoe@gmail.com>

diff --git a/net-misc/dropbox/files/dropbox.initd b/net-misc/dropbox/files/dropbox.initd
--- a/net-misc/dropbox/files/dropbox.initd
+++ b/net-misc/dropbox/files/dropbox.initd
@@ -1,65 +1,96 @@
 #!/sbin/openrc-run
-# Copyright 1999-2016 Gentoo Foundation
+# Copyright 1999-2019 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License, v2 or later
 
 depend() {
-    need localmount net
-    after bootmisc
+	need localmount net
+	after bootmisc
 }
 
 start() {
-    local tmpnice="${NICE:+"--nicelevel "}${NICE}"
-    local tmpionice="${IONICE:+"--ionice "}${IONICE}"
-    local started=""
+	local tmpnice="${NICE:+--nicelevel ${NICE}}"
+	local tmpionice="${IONICE:+--ionice ${IONICE}}"
+	local started=""
 
-    ebegin "Starting dropbox"
-    for dbuser in ${DROPBOX_USERS}; do
-	local homedir=$(eval echo ~${dbuser})
-	if test -d "${homedir}" && \
-	    echo 0 > ${homedir}/.dropbox/dropbox.pid && \
-	    start-stop-daemon -S -b \
-	    ${tmpnice} ${tmpionice} \
-	    -u ${dbuser} -v \
-	    -p ${homedir}/.dropbox/dropbox.pid \
-	    -e HOME=${homedir} \
-	    -x /opt/bin/dropbox; then
-	    started="${started} ${dbuser}"
+	ebegin "Starting dropbox"
+	for dbuser in ${DROPBOX_USERS}; do
+		local homedir="$(_get_dbuser_homedir)"
+		local pidfile="${homedir}/.dropbox/dropbox.pid"
+
+		if _start_dbuser; then
+			started="${started} ${dbuser}"
+		else
+			eend $?
+			eerror "Failed to start dropbox for ${dbuser}"
+			if [ -n "${started}" ]; then
+				eerror "Stopping already started dropbox"
+				DROPBOX_USERS="${started}" stop
+			fi
+			return 1
+		fi
+	done
+	if [ -z "${started}" ];then
+		eerror "No dropbox started"
+		eend 1
 	else
-	    eend $?
-	    eerror "Failed to start dropbox for ${dbuser}"
-	    if [ -n "${started}" ]; then
-		eerror "Stopping already started dropbox"
-		DROPBOX_USERS=${started} stop
-	    fi
-	    return 1
+		eend 0
 	fi
-    done
-    if [ -z "${started}" ];then
-	eerror "No dropbox started"
-	eend 1
-    else
-	eend 0
-    fi
 }
 
 stop() {
-    local retval=0
-    ebegin "Stopping dropbox"
-    for dbuser in ${DROPBOX_USERS}; do
-	local homedir=$(eval echo ~${dbuser})
-	start-stop-daemon --stop \
-	    --pidfile ${homedir}/.dropbox/dropbox.pid || retval=$?
-    done
-    eend ${retval}
+	local retval=0
+	ebegin "Stopping dropbox"
+	for dbuser in ${DROPBOX_USERS}; do
+		local homedir="$(_get_dbuser_homedir)"
+		local pidfile="${homedir}/.dropbox/dropbox.pid"
+
+		start-stop-daemon --stop \
+			--pidfile "${pidfile}" \
+			--user "${dbuser}" || retval=$?
+	done
+	eend ${retval}
 }
 
 status() {
-    for dbuser in ${DROPBOX_USERS}; do
-	local homedir=$(eval echo ~${dbuser})
-	if [ -e ${homedir}/.dropbox/dropbox.pid ] ; then
-            echo "dropboxd for USER $dbuser: running."
-	else
-            echo "dropboxd for USER $dbuser: not running."
+	for dbuser in ${DROPBOX_USERS}; do
+		local homedir="$(_get_dbuser_homedir)"
+		local pidfile="${homedir}/.dropbox/dropbox.pid"
+
+		if _check_pid; then
+			echo "dropboxd for USER ${dbuser}: running."
+		else
+			echo "dropboxd for USER ${dbuser}: not running."
+		fi
+	done
+}
+
+_start_dbuser() {
+	[ -d "${homedir}" ] || return
+	if _check_pid; then
+		echo "dropbox already started for user ${dbuser}"
+		return 0
 	fi
-    done
+
+	echo 0 >"${pidfile}" || return
+	start-stop-daemon --start --background \
+		${tmpnice} ${tmpionice} \
+		--user "${dbuser}" \
+		--pidfile "${pidfile}" \
+		--env HOME="${homedir}" \
+		--exec /opt/bin/dropbox
+}
+
+_get_dbuser_homedir() {
+	local homedir
+	homedir="$(getent passwd "${dbuser}" | cut -d: -f6)" || return
+	printf '%s' "${homedir}"
+}
+
+_check_pid() {
+	[ -e "${pidfile}" ] || return
+
+	local pid
+	pid="$(pgrep -u "${dbuser}" dropbox)" || return
+
+	[ "$(<"${pidfile}")" -eq "${pid}" ]
 }
