sci-misc/boinc: V7.16.14 bump, EAPI 7 upgrade, bug fixes, GLEP 81
This version bump also fixes the following issues:
* The user/group management is now done according to GLEP 81
* /etc/init.d/boinc: Ensure correct RUNTIMEDIR permissions (#684074)
* /etc/init.d/boinc: The password does no longer need to be submitted
* Hardcoded library search paths to /lib and /usr/lib have been
  removed or switched to /lib64 and /usr/lib64, if those are the
  regular library directories on the emerging system. (#732024)

Closes: https://bugs.gentoo.org/684074
Closes: https://bugs.gentoo.org/717580
Closes: https://bugs.gentoo.org/732024
Package-Manager: Portage-3.0.9, Repoman-3.0.2
Signed-off-by: Sven Eden <sven.eden@prydeworx.com>

diff --git a/sci-misc/boinc/files/boinc.init.in b/sci-misc/boinc/files/boinc.init.in
--- a/sci-misc/boinc/files/boinc.init.in
+++ b/sci-misc/boinc/files/boinc.init.in
@@ -18,12 +18,12 @@ create_work_directory() {
 			eerror "Directory ${RUNTIMEDIR} could not be created!"
 			return 1
 		fi
+	fi
 
-		# ensure proper ownership
-		if ! chown "${USER}:${GROUP}" "${RUNTIMEDIR}"; then
-			eerror "Changing ownership of '${RUNTIMEDIR}' to '${USER}:${GROUP}' failed!"
-			return 1
-		fi
+	# ensure proper ownership
+	if ! chown "${USER}:${GROUP}" "${RUNTIMEDIR}"; then
+		eerror "Changing ownership of '${RUNTIMEDIR}' to '${USER}:${GROUP}' failed!"
+		return 1
 	fi
 
 	if [ ! -e "${RUNTIMEDIR}"/ca-bundle.crt ]; then
@@ -117,17 +117,6 @@ env_check() {
 	return 0
 }
 
-need_passwd_arg() {
-	local vers=$(${BOINCBIN} --version | tr -d .)
-	[ -z "${vers}" ] && vers="00"
-	[ $(expr substr "${vers}" 1 2) -lt 74 ] && return 0
-
-	# From version 7.4 on, the default is to read
-	# gui_rpc_auth.cfg for the password.
-
-	return 1
-}
-
 start_pre() {
 	env_check || return 1
 	create_work_directory || return 1
@@ -164,7 +153,6 @@ start() {
 }
 
 attach() {
-	local password=""
 	local url=""
 	local key=""
 
@@ -182,14 +170,10 @@ attach() {
 		"${RC_SERVICE}" start
 	fi
 
-	if need_passwd_arg; then
-		password="--passwd \"$(cat "${RUNTIMEDIR}/gui_rpc_auth.cfg")\""
-	fi
-
 	ebegin "${RC_SVCNAME}: Attaching to project"
 	start-stop-daemon --user "${USER}:${GROUP}" --quiet \
 		--chdir "${RUNTIMEDIR}" --exec "${BOINCCMD}" \
-		-- ${password} --project_attach ${url} ${key}
+		-- --project_attach ${url} ${key}
 	eend $?
 
 	sleep 10
@@ -197,14 +181,9 @@ attach() {
 }
 
 stop() {
-	local password=""
 	local stop_timeout="SIGTERM/60/SIGTERM/30/SIGKILL/30"
 
 	env_check || return 1
-
-	if need_passwd_arg; then
-		password="--passwd \"$(cat "${RUNTIMEDIR}/gui_rpc_auth.cfg")\""
-	fi
 
 	ebegin "Stopping ${RC_SVCNAME}"
 	start-stop-daemon --stop --quiet --progress \
@@ -216,19 +195,13 @@ stop() {
 resume() {
 	env_check || return 1
 
-	local password=""
-
-	if need_passwd_arg; then
-		password="--passwd \"$(cat "${RUNTIMEDIR}/gui_rpc_auth.cfg")\""
-	fi
-
 	for url in $(cd "${RUNTIMEDIR}" ; \
-		  "${BOINCCMD}" ${password} --get_project_status | \
+		  "${BOINCCMD}" --get_project_status | \
 		  sed -n 's/\s*master URL: //p'); do
 		ebegin "Resuming ${url}"
 		start-stop-daemon --user "${USER}:${GROUP}" --quiet \
 			--chdir "${RUNTIMEDIR}" --exec "${BOINCCMD}" \
-			-- ${password} --project ${url} resume
+			-- --project ${url} resume
 		eend $?
 	done
 }
@@ -236,19 +209,13 @@ resume() {
 suspend() {
 	env_check || return 1
 
-	local password=""
-
-	if need_passwd_arg; then
-		password="--passwd \"$(cat "${RUNTIMEDIR}/gui_rpc_auth.cfg")\""
-	fi
-
 	for url in $(cd "${RUNTIMEDIR}" ; \
-		  "${BOINCCMD}" ${password} --get_project_status | \
+		  "${BOINCCMD}" --get_project_status | \
 		  sed -n 's/\s*master URL: //p'); do
 		ebegin "Suspending ${url}"
 		start-stop-daemon --user "${USER}:${GROUP}" --quiet \
 			--chdir "${RUNTIMEDIR}" --exec "${BOINCCMD}" \
-			-- ${password} --project ${url} suspend
+			-- --project ${url} suspend
 		eend $?
 	done
 }
