sys-kernel/linux-firmware: Update from review
Make the call to rdfind optional via use-flag
This call was added by upstream for creating symlinks
on duplicate files

Signed-off-by: Mike Pagano <mpagano@gentoo.org>

diff --git a/sys-kernel/linux-firmware/files/linux-firmware-remove-rdfind-dep-and-use.patch b/sys-kernel/linux-firmware/files/linux-firmware-remove-rdfind-dep-and-use.patch
--- a/sys-kernel/linux-firmware/files/linux-firmware-remove-rdfind-dep-and-use.patch
+++ b/sys-kernel/linux-firmware/files/linux-firmware-remove-rdfind-dep-and-use.patch
@@ -1,18 +1,15 @@
---- a/copy-firmware.sh	2023-11-25 14:59:33.463158589 -0500
-+++ b/copy-firmware.sh	2023-11-25 15:00:31.936152432 -0500
-@@ -69,11 +69,6 @@ if [ -z "$destdir" ]; then
+--- a/copy-firmware.sh	2023-11-25 18:07:49.362441380 -0500
++++ b/copy-firmware.sh	2023-11-25 18:19:03.612907595 -0500
+@@ -69,7 +69,7 @@ if [ -z "$destdir" ]; then
  	exit 1
  fi
  
 -if ! which rdfind 2>/dev/null >/dev/null; then
--	echo "ERROR: rdfind is not installed"
--	exit 1
--fi
--
- # shellcheck disable=SC2162 # file/folder name can include escaped symbols
- grep -E '^(RawFile|File):' WHENCE | sed -E -e 's/^(RawFile|File): */\1 /;s/"//g' | while read k f; do
-     test -f "$f" || continue
-@@ -87,14 +82,6 @@ grep -E '^(RawFile|File):' WHENCE | sed
++if [ -n "$LINUX_FIRMWARE_DO_DEDUPE" ] && ! which rdfind 2>/dev/null >/dev/null; then
+ 	echo "ERROR: rdfind is not installed"
+ 	exit 1
+ fi
+@@ -87,13 +87,15 @@ grep -E '^(RawFile|File):' WHENCE | sed
      fi
  done
  
@@ -23,7 +20,15 @@
 -	$verbose "Correcting path for $l"
 -	ln -fs "$(realpath --relative-to="$(dirname "$(realpath -s "$l")")" "$target")" "$l"
 -done
--
++if [ -n "$LINUX_FIRMWARE_DO_DEDUPE" ]; then
++	$verbose "Finding duplicate files"
++	rdfind -makesymlinks true -makeresultsfile false "$destdir" >/dev/null
++	find "$destdir" -type l | while read -r l; do
++		target="$(realpath "$l")"
++		$verbose "Correcting path for $l"
++		ln -fs "$(realpath --relative-to="$(dirname "$(realpath -s "$l")")" "$target")" "$l"
++	done
++fi
+ 
  # shellcheck disable=SC2162 # file/folder name can include escaped symbols
  grep -E '^Link:' WHENCE | sed -e 's/^Link: *//g;s/-> //g' | while read f d; do
-     if test -L "$f$compext"; then
