sys-firmware/intel-microcode: avoid mount-boot if ROOT is set
and:
- rdep on iucode_tool for .install hook
- USE=hostonly: iucode_tool is executed in pkg_preinst and should therefore be
an idep instead of a rdep (not that it really makes a functional difference
since it is bdep anyway)
- rework REQUIRED_USE: the *.install hooks require the split-ucode to be
present. Since with USE=dist-kernel, USE=initramfs does not install intel-uc.img
(instead it is delegared to installkernel via the *.install hooks)  we need
always split-ucode with dist-kernel.
- *.install: exit gracefully if no ucode installed

this mirrors recent changes in sys-kernel/linux-firmware

Signed-off-by: Andrew Ammerlaan <andrewammerlaan@gentoo.org>

diff --git a/sys-firmware/intel-microcode/files/35-intel-microcode-systemd.install b/sys-firmware/intel-microcode/files/35-intel-microcode-systemd.install
--- a/sys-firmware/intel-microcode/files/35-intel-microcode-systemd.install
+++ b/sys-firmware/intel-microcode/files/35-intel-microcode-systemd.install
@@ -35,13 +35,18 @@ opts=(
 	--no-downgrade
 )
 
-if [[ ${KERNEL_INSTALL_VERBOSE} == 1 ]]; then
-	echo "Generating Intel CPU Microcode early initramfs image..."
-	opts+=(
-		--list-all
-		--list
-	)
-fi
+if [[ -d /lib/firmware/intel-ucode ]]; then
+	if [[ ${KERNEL_INSTALL_VERBOSE} == 1 ]]; then
+		echo "Generating Intel CPU Microcode early initramfs image..."
+		opts+=(
+			--list-all
+			--list
+		)
+	fi
 
-iucode_tool /lib/firmware/intel-ucode "${opts[@]}" ||
-	{ echo "iucode_tool failed" && exit 1; }
+	iucode_tool /lib/firmware/intel-ucode "${opts[@]}" ||
+		{ echo "iucode_tool failed" && exit 1; }
+else
+	[[ ${KERNEL_INSTALL_VERBOSE} == 1 ]] && echo \
+		"No Intel CPU Microcode installed, nothing to do here."
+fi
